# Generated by Django 6.0.4 on 2026-04-30 15:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0004_alter_tour_tour_instance_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tour",
            options={"ordering": ["start_date"]},
        ),
        migrations.RenameField(
            model_name="tour",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tour",
            old_name="price_zar",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="available_slots",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="max_guests",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="scheduled_end",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="scheduled_start",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="tour_instance_code",
        ),
        migrations.AddField(
            model_name="tour",
            name="end_date",
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tour",
            name="start_date",
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tour",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="TourBooking",
        ),
    ]
