# Generated by Django 6.0.4 on 2026-05-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_options_rename_title_tour_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tour',
            name='best_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='center_pin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(default='ZA', max_length=2),
        ),
        migrations.AddField(
            model_name='tour',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='group_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='starting_from',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('city', 'City'), ('landmark', 'Landmark'), ('multi-city', 'Multi-City'), ('multi-country', 'Multi-Country')], default='city', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TourHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('pin', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('img', models.URLField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
