# Generated by Django 6.0.4 on 2026-05-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_options_tour_best_time_tour_center_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_code', models.CharField(help_text='ISO Code (e.g., ZA, ZW)', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('flag', models.CharField(help_text='Emoji flag (e.g., 🇿🇦)', max_length=10)),
                ('tagline', models.CharField(max_length=200)),
                ('card_image', models.CharField(max_length=500)),
                ('hero_image', models.CharField(max_length=500)),
                ('center_lat', models.FloatField(default=0.0)),
                ('center_lon', models.FloatField(default=0.0)),
                ('zoom', models.IntegerField(default=5)),
                ('topo_id', models.CharField(help_text='ISO alpha-3 (e.g., ZAF)', max_length=10)),
                ('color', models.CharField(default='#5c7a3e', help_text='Hex color code', max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RemoveField(
            model_name='touritineraryitem',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='List of {"icon": "🏔️", "text": "..."} objects'),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, help_text='List of {"day": 1, "title": "...", "desc": "...", "pin": "slug", "img": "url"}'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='best_time',
            field=models.CharField(blank=True, help_text="e.g., 'Oct - Apr'", max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '3-7 days'", max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='starting_from',
            field=models.CharField(blank=True, help_text="Just the number, e.g., '245'", max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country'),
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('slug', models.SlugField(help_text='Unique ID for map (e.g., cape-town)', primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='tours.country')),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='center_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.pin'),
        ),
        migrations.DeleteModel(
            name='TourHighlight',
        ),
        migrations.DeleteModel(
            name='TourItineraryItem',
        ),
    ]
